### PR TITLE
Add TypeScript Declaration for jsonpath-plus

### PR DESCRIPTION
**Pull request by Kiyozz**
Leave any comments on missing types and documentations.

Some fields I do not know the type is typed `any`

### CODE REVIEW

**Comment by Kiyozz** [comment]
Not fully working, stand by!

**Comment by Kiyozz** [comment]
Feel free to do suggestions about wrong return types and types 👍

**Comment by brettz9** [comment]
Would you mind taking a look at the extra commits I added (for which you'd need to run `npm install` again to get `typedoc` installed locally)?

I figure this is a good opportunity for me to personally dip a little into TS and see how it may work for us for building docs given your providing a helpful example to start with, but with the basic options for typedoc at least, I couldn't get any types to show up in the resulting docs when feeding it our `src` directory containing your `.d.ts` file. Do you know if we have to pass extra config to `typedoc` or something else? I just did `typedoc --out docs/ts src`.

If I can see that it is working for doc generation, I'll more happily accept this PR and forego duplicating docs in plain jsdoc or struggling on how to mix the `.d.ts` and js-with-jsdoc files so they can build on one another without duplication, e.g., my adding `@typedef`s within js if that would even work (out of curiosity even if we don't go that way, do you know if it does?).

This also ought to motivate me to keep the ts up to date if we're depending on it for our docs.

Thanks for this!

**Comment by Kiyozz** [comment]
You don't need to compile `d.ts` files, they are there to add types for libraries when imported from scripts. I removed `typescript` script in `package.json`.

I tested it with a new project, linked the package. When you import it, in `ts` and `js` file, your IDE will provide IntelliSense.

The doc generated with `npm run build-docs`
[docs.zip](https://github.com/s3u/JSONPath/files/3287651/docs.zip)

The last thing to do is to check if the `.d.ts` is correct. I do not know exactly all the things the library provides.

Any `@typedef` or any JSDoc is now useless.

To provide IntelliSense when developing the library, you'll need to turn it to TypeScript (`.js` to `.ts`)

**Comment by brettz9** [comment]
Thanks very much for this and the info. I see it building for me now locally with the `--includeDeclarations`.

Re: compiling files, what about adding the `--noEmit` flag to the `tsc src/jsonpath.d.ts` command instead so as to validate?

Regarding reviewing the contents, I hope I may get to this in the next few days.

**Comment by Kiyozz** [comment]
There is nothing to check in d.ts because this is ambient context.

Waiting for you to check if the API is correct in jsonpath.d.ts

**Comment by brettz9** [comment]
Re: d.ts, I understand, but the file can become poorly-formed such that passing the `tsc` will give an error rather than do nothing. Of course a Typescript linter could do more, but since we have typescript already in use, I'd like to keep a sanity check there to ensure it doesn't get broken, even as I am clear that it isn't functioning code.

**Comment by Kiyozz** [comment]
I don’t think `tsc` will provide error on .d.ts if it’s mal formed because it doesn’t rely on external library (not even node). `tsc` will just say nothing in my opinion.

If jsonpath.js API changes, no error will be in .d.ts. There are not connected to each other

**Comment by brettz9** [comment]
It does, I tried it. At least a well-formedness checker--not necessarily a validator though.

**Comment by brettz9** [comment]
Have come down with a cold, but have at least been reading through the typescript docs to be able to do a more educated review.

**Comment by brettz9** [comment]
Still going through the TS docs (slowed down by my cold), but I was wondering how crazy of an idea it would be to use TypeScript in our source instead so that, besides regular JavaScript builds, we could actually compile to WebAssembly (using say AssemblyScript).

This might speed up performance, something that is important with this kind of library, even if the kind of performance gains might not be as much as they would for number crunching.

@andykais

**Comment by Kiyozz** [comment]
Migrating to TypeScript will emit declarations based on the source (if you make comments of functions/class, they will be in declarations too).

I’m always for using TypeScript, for any projects. 😄

**Comment by brettz9** [comment]
Thanks, yes, understood. I have gotten the basic idea now, but just need to delve into the specifics of the syntax to be able to evaluate your PR more intelligently, as well as offer, if needed, any replacements.

**Comment by brettz9** [comment]
Very sorry, but it seems it is going to take me quite a bit longer to be able to get to reviewing this. However, since it doesn't modify our core files, if you, or someone else familiar with the library, feels confident it matches, I can go ahead and merge.

And if someone feels inspired to change the source to TypeScript, as long as there is a build process leading to plain JavaScript (including non-minified so results can be confirmed), I'd be open to that as well, particularly if it supported the [subset of TypeScript required by AssemblyScript](https://docs.assemblyscript.org/) to compile to WebAssembly to see what kind of performance gains there might be.

**Comment by Kiyozz** [comment]
Can we get this merged?

**Comment by brettz9** [comment]
I don't have time now to review for accuracy, but if you feel it should be accurate enough, I can do so. I assume this shouldn't be a breaking change for anyone?

**Comment by Kiyozz** [comment]
JavaScript users will have no problems.

TypeScript users can have errors when using a method/object property not
defined in the TypeScript definition (the method/property is present). This
is only if I was wrong in the definition.

Le mer. 7 août 2019 à 19:45, Brett Zamir <notifications@github.com> a
écrit :

**Comment by brettz9** [comment]
The TypeScript declaration has been incorporated in 38af31df124b4bbe12e3ad7ed720899da0e4597a and released in npm v1.0.0.

If anyone comes across this issue in finding a TypeScript issue, feel free to file a new issue or PR.

(Note that the version 1.0.0 does not signify any increase in stability for the project, but should allow projects to more easily benefit from new non-breaking features, as they can peg their dependencies to the minor version going forward.)

Thanks for the PR!

**Pull request closed without merging**
